# Your name and what you do
name: Bonjour Océane

# Profile picture TO CHANGE
#picture: assets/images/profile.jpg

# your url: http://USERNAME.github.io
url: https://benjaminformaticien.info

# do you want to display social media links? true or false
social-media: false
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
#twitter: mytwitter
#linkedin: benjaminformaticien
#reddit: Benjaminateur
#github: benjaminformaticien
#email: benjaminformaticien@gmail.com

# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: false

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list: 
Vous avez été sélectionnée pour participer à une épreuve de dégustation.
Rendez-vous Avenue Gustave Eiffel, le 30 janvier 2022.

Une tenue correcte est éxigée.

Un chauffeur vous déposera au lieu de rendez-vous.
Un de nos gardes du corps veillera à la sécurité de Jibao pendant l épreuve.

# do you want to display a projects section? true or false
projects: false

# add your projects here
#project-list:
#    Eve:
#        name: Test
#        description: Ultra Minimal Single-page Jekyll Template for Building Personal Portfolio Websites
#        url: https://github.com/jibolash/Eve
#    World-Cup-History:
#        name: Test2
#        description: npm package for FIFA World cup historical data
#        url: https://github.com/jibolash/world-cup-history
#    Tweeter:
#        name: Test3
#        description: A Twitter inspired web application built with Angular 5
#        url: https://tweetermum.herokuapp.com
#    Transcend:
#        name: Test4
#        description: An android app for meditation and mindfulness
#        url: https://github.com/Khosbayar/Transcend


# do you want to display the theme attribution? true or false
footer: false

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
